### ISSUE TITLE
Update Tensorflow Version

### ISSUE THREAD

**Issue by gdj0nes** [aws/sagemaker-tensorflow-extensions#26]
It is confusing that the extensions are supported for TF 1.7 and above but the you also need to install for a specific version? The releases seems to suggest support only up to 1.9 but the commit messages suggest compatibility up to 1.11.

**Comment by owen-t** [comment]
The PyPI documentation is wrong and we'll correct this. We support TF 1.7 through TF 1.11.

Yes, you need to install the correct version of sagemaker-tensorflow for your tensorflow install. Because there are different installations of TensorFlow (e.g. builds specific for mkl, gpu devices), it's hard for us to use `setuptools` dependencies to capture this. We considered adding some logic in our `setup.py` to install the correct version of sagemaker tensorflow for the installed version of TF, but decided against doing that was it was difficult to own and manage with release branching.
