### ISSUE TITLE
TF 2.0 support?

### ISSUE THREAD

**Issue by jamiekang** [aws/sagemaker-tensorflow-extensions#71]
Hi, will this extensions work with TensorFlow 2?

**Comment by knakad** [comment]
Thanks for reaching out!
Absolutely, take a look at the versions that start with 2 =)
https://pypi.org/project/sagemaker-tensorflow/#history

Example: https://pypi.org/project/sagemaker-tensorflow/2.1.0.1.0.0/

Hope that helps!

**Comment by loodvn** [comment]
Hey there! 

Based on this and #56, there still seems to be confusion around whether TF2 is supported - mainly because the README on master still says "TensorFlow versions 1.7-1.15.2". This was initially why we've been holding back on a TF 2.0 migration for one of our models at work 😂.. 

I see there's an updated readme (corresponding to the latest PyPI release descriptions) in the tf-2 branch. 

I know there must be some reason the branches aren't merged, but maybe there could be some simple explanation until that time, like "[...] TensorFlow versions 1.7-1.15.2. TF 2 support is also available in the tf-2 branch and on PyPI (all the versions that start with 2: https://pypi.org/project/sagemaker-tensorflow/#history)."

What do you think? If I hadn't gone into the closed issues and seen these two threads, I would've again concluded that we're still waiting on TF 2 here 🤷
